require 'anygood/clients/client'
require 'anygood/clients/imdb'
require 'anygood/clients/rotten_tomatoes'
require 'anygood/movie'
require 'anygood/movie_cache'
require 'anygood/movie_matcher'
require 'anygood/movie_fetcher'
require 'anygood/movie_importer'
